{{- if .Values.ack.s3.enabled }}
apiVersion: s3.services.k8s.aws/v1alpha1
kind: Bucket
metadata:
  name: {{ .Release.Name }}-ci-logs
  labels:
    {{- include "temporalci.labels" . | nindent 4 }}
spec:
  name: {{ .Values.ack.s3.bucketName }}
  tagging:
    tagSet:
      - key: app
        value: temporalci
{{- end }}
