{{- if .Values.secrets.aws.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    {{- include "temporalci.labels" . | nindent 4 }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "{{ .Values.secrets.prefix }}/github-webhook-secret"
        objectType: "secretsmanager"
      - objectName: "{{ .Values.secrets.prefix }}/github-token"
        objectType: "secretsmanager"
    region: {{ .Values.aws.region }}
{{- end }}
