{{- if .Values.secrets.aws.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "temporalci.labels" . | nindent 4 }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "{{ .Values.secrets.prefix }}/github-webhook-secret"
        objectType: "secretsmanager"
      - objectName: "{{ .Values.secrets.prefix }}/github-token"
        objectType: "secretsmanager"
      {{- if .Values.githubApp.enabled }}
      - objectName: "{{ .Values.secrets.prefix }}/github-app-key"
        objectType: "secretsmanager"
      {{- end }}
  secretObjects:
    - secretName: {{ .Release.Name }}-secrets
      type: Opaque
      data:
        - objectName: "{{ .Values.secrets.prefix }}/github-webhook-secret"
          key: github-webhook-secret
        - objectName: "{{ .Values.secrets.prefix }}/github-token"
          key: github-token
{{- end }}
