{{- if and .Values.secrets.local.enabled (or .Values.secrets.local.githubWebhookSecret .Values.secrets.local.githubToken) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    {{- include "temporalci.labels" . | nindent 4 }}
type: Opaque
data:
  github-webhook-secret: {{ .Values.secrets.local.githubWebhookSecret | b64enc | quote }}
  github-token: {{ .Values.secrets.local.githubToken | b64enc | quote }}
{{- end }}
