apiVersion: v1
kind: ServiceAccount
metadata:
  name: temporalci-worker
  labels:
    {{- include "temporalci.labels" . | nindent 4 }}
  {{- with .Values.serviceAccounts.worker.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ . }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: temporalci-webhook
  labels:
    {{- include "temporalci.labels" . | nindent 4 }}
  {{- with .Values.serviceAccounts.webhook.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ . }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: temporalci-ci-job
  labels:
    {{- include "temporalci.labels" . | nindent 4 }}
  {{- with .Values.serviceAccounts.ciJob.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ . }}
  {{- end }}
