{{- if .Values.temporalWeb.loadBalancer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web-lb
  labels:
    {{- include "temporalci.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: temporal
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: web
{{- end }}
