apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ci-worker
  labels:
    {{- include "temporalci.labels" . | nindent 4 }}
    app.kubernetes.io/component: ci-worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      {{- include "temporalci.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ci-worker
  template:
    metadata:
      labels:
        {{- include "temporalci.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: ci-worker
    spec:
      serviceAccountName: temporalci-worker
      containers:
        - name: worker
          image: "{{ .Values.image.registry }}{{ if .Values.image.registry }}/{{ end }}{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          command: ["/usr/local/bin/worker"]
          env:
            - name: TEMPORAL_HOST_PORT
              value: "{{ .Release.Name }}-frontend:7233"
            - name: TEMPORAL_WEB_URL
              value: "{{ .Values.worker.temporalWebURL | default "" }}"
            {{- if .Values.secrets.local.enabled }}
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: github-token
            {{- end }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
